name: noising-probing
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - h5py
  - tqdm
  - pandas
  - python=3.12.9
  - pytorch
  - pytorch-cuda
  - scikit-learn
  - torchaudio
  - torchvision
