name: another-name
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - tqdm
  - pandas
  - python=3.12.9
  - scikit-learn
  - pip

# pip install torch==2.4.1+rocm6.1 torchvision==0.19.1+rocm6.1 --index-url https://download.pytorch.org/whl/rocm6.1
